### ISSUE TITLE
error running on local, set bing search api key only

### ISSUE THREAD

**Issue by seshubonam** [leptonai/search_with_lepton#11]
Key Z_CyH0ytaGuT7g3XCdh2o not found, will generate again.
| ERROR    | __main__:query_function:503 - encountered error: module 'openai' has no attribute 'OpenAI'

[
<img width="1440" alt="Screenshot 2024-01-27 at 7 10 45 AM" src="https://github.com/leptonai/search_with_lepton/assets/1757478/a8106379-a72f-472a-b85b-62a8b473300a">
](url)

**Comment by seshubonam** [comment]
used pip install, and build commands as shown in homepage. do i need to use lepton workspace key as well for local deployment ?

**Comment by Yangqing** [comment]
Thanks - for the first error, I believe it is due to the openai version error. Could you try openai version >1.0.0?
```
pip install openai>=1.0
```

For local deployment - yes, you will need the lepton workspace token to call the LLM apis and the KV. Sorry it wasn't clear enough in the doc and output message - will put up some code change to reflect that.
